---
gitlab_edition: gitlab-ee
gitlab_version: latest
gitlab_external_url: "https://primary.example.com"
gitlab_db_password: "changeme_db_password"
gitlab_geo_primary_role_enabled: true
gitlab_geo_node_name: "primary"
gitlab_postgresql_shared_preload_libraries: "pg_stat_statements"
